apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  type: NodePort # only container to container communication is possible
  ports:
  - port: 5432
    nodePort: 30001
