apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  type: ClusterIP # only container to container communication is possible
  ports:
   - protocol: TCP
     port: 5432
     targetPort: 5432